name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main   # Change this if your default branch is not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow pushing to gh-pages

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist   # adjust if your build output is somewhere else
